/*
 * generated by Xtext 2.25.0
 */
package com.mike.berezhkov.huawei.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CPoCPUiModule extends AbstractCPoCPUiModule {

	public CPoCPUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
